### PR TITLE
MAL API Workaround

### PR DESCRIPTION
**Pull request by MCAxiaz**
yes.

### CODE REVIEW

**Comment by tmathura** [comment]
Any idea when this will be implemented?

**Comment by MCAxiaz** [comment]
Done. Hopefully didn't mess anything up since I'm a completely monkey with git.

**Comment by inorichi** [comment]
Err, sorry, the PR is messed up. I was going to push to your branch but the history was really wrong and thought you knew how to fix it.

I'd recommend you to close this PR and create a new one with my branch `pr/1647`, since it's already rebased and you'll get the contribution.

**Comment by MCAxiaz** [comment]
How about now. Sorry for making you deal with this shit. Thought this was a good opportunity to actually learn git so I tried fixing it again.

**Comment by inorichi** [comment]
Yes, it's fixed now.

**Comment by inorichi** [comment]
No, you have to login again.

**Comment by dhanjit** [comment]
When would this be pushed to stable release?

**Pull request merged**
