### PR TITLE
skip ci in commit message condition check

### PR DESCRIPTION
**Pull request by sainAk**

### CODE REVIEW

**Comment by arkon** [comment]
Can the jobs have more descriptive names?

**Comment by sainAk** [comment]
yeah what name do you want

**Comment by sainAk** [comment]
@arkon about your commit e637f22
it will also skip builds of other branches on a fork repo like mine

**Comment by arkon** [comment]
> it will also skip builds of other branches on a fork repo like mine

Yeah, my bad. It's an unintentional side effect of me not wanting it to run for other branches in this main repo, but I'm not sure if there's a good workaround for that.

**Pull request merged**
