### PR TITLE
Bugfix. Sharing images with very long name

### PR DESCRIPTION
**Pull request by Pavkazzz**
Fix sharing images, which generate very long image name for sharing. 
Currently ocures on readmanga parser - this manga: http://readmanga.me/neveroiatnye_prikliucheniia_djodjo_chast_8__djodjolion__cvetnaia_versiia_

### CODE REVIEW

**Comment by AviKav** [comment]
"I don't think that function means what you think it means."

**Comment by Pavkazzz** [comment]
@avikav doesn't get what you mean. Now we have a bug with images with very long names, this pull request fix it

**Comment by AviKav** [comment]
```kotlin
val string = "1234567890"
println(string.dropLast(6)) // 1234
```

**Comment by Pavkazzz** [comment]
Yes, in practice you cannot create file with more then 255 length in android

**Comment by CarlosEsco** [comment]
Function drop last n

**Comment by CarlosEsco** [comment]
Meaning it's gonna drop 200 characters Everytime. If you don't believe me check neko save as I had pulled this already.

**Comment by Pavkazzz** [comment]
@carlosesco you absolutely right, what should i use to reduce big string to short one?

**Comment by AviKav** [comment]
@Pavkazzz 
1. `.dropLast(n)` means that the string will be empty if it's length is less than or equal to `n`.
2. There are better workarounds for filename limits that involve breaking the file name onto the path
3. Dropping characters over if the first string's length is over 200 would still leave at least 46 characters left to fill

**Comment by inorichi** [comment]
Use `.take(225)`. That should leave enough room for the page number and extension (we should consider the limit to be 240)

**Comment by Pavkazzz** [comment]
@inorichi That's what i want, thank you!

**Pull request merged**
