### PR TITLE
Some more forgotten translations 2

### PR DESCRIPTION
**Pull request by j2ghz**

### CODE REVIEW

**Comment by yshalsager** [comment]
Arabic seems to be okay.

**Comment by asereze** [comment]
Sardinian is fine as well.

**Comment by alessandrojean** [comment]
The Brazilian Portuguese translation in the three PRs is outdated and doesn't need to be saved.

**Comment by arkon** [comment]
Closing these PRs since we didn't seem to get any issues. We can still reference these if needed.

**Pull request closed without merging**
