### PR TITLE
Clear history

### PR DESCRIPTION
**Pull request by historiatachi**
As Arkon say to submit pull request for this then of course I would! I just want this feature.. please! :'(

https://github.com/inorichi/tachiyomi/issues/3812#issuecomment-693523395

### CODE REVIEW

**Comment by CarlosEsco** [comment]
... so you opened a pull request without the change and just did random commits..

**Comment by historiatachi** [comment]
Oh cmon what did I do wrong again? It's not even to open this pull request and you just closed it T.T

**Comment by Soitora** [comment]
Pull Request has nothing to do with wanting a feature, it's when you've written code and want it quality checked and then added to the app. You've done nothing like that.

**Comment by AbdullahM0hamed** [comment]
When Arkon said submit a PR if you want it ASAP - he basically meant "I'm not adding this feature any time soon, but I'm willing to let you add this feature if you want". Pull Requests are not super issues.

**Pull request closed without merging**
