### PR TITLE
Single tap up/down scrolls up/down on webtoon viewer.

### PR DESCRIPTION
**Pull request by unnurq**
Makes it more intuitive.

### CODE REVIEW

**Comment by inorichi** [comment]
Long ago I was thinking about something like this:
```
+---+---+---+
| P | P | P |   P: Previous
+---+---+---+
| P | M | N |   M: Menu
+---+---+---+
| N | N | N |   N: Next
+---+---+---+
```

How does it sound?

**Comment by hXtreme** [comment]
Kindle devices have something similar so it might be better to mimic them. I'm assuming that they used their massive amounts of usage data to fine tune their UI.

**Comment by inorichi** [comment]
@unnurq, what do you think about my proposal?

**Comment by 0450** [comment]
i think having the middle with all menu would be better.

**Comment by 0450** [comment]
maybe the L shaped can be an option too.

**Comment by hXtreme** [comment]
Can you please wait a bit to merge this? I've opened a [PR](https://github.com/unnurq/tachiyomi/pull/1) on @unnurq 's fork with a number of additions.

If you (@inorichi ) merges this i can also just open a PR directly to master

**Comment by arkon** [comment]
Closing in favour of #2152

**Pull request closed without merging**
