### PR TITLE
Issue 773 Add images and 'view chapters' to library updates.

### PR DESCRIPTION
**Pull request by CarlosEsco**
#773 

cover image in library updates view
image

Open Manga Option from 3 dot menu
image

### CODE REVIEW

**Comment by NoodleMage** [comment]
Make it that when you press the cover it opens the manga (like in recently read). 

Also with the rewrite from https://github.com/inorichi/tachiyomi/tree/conductor. This code will probably be obsolete

**Comment by inorichi** [comment]
In fact I won't merge any change to the `ui` package (excluding reader and settings) until that branch is merged.

**Comment by CarlosEsco** [comment]
Is there estimated date of when the merger is gonna occur?  You can close this and I i will redo after the merger.  @NoodleMage  note taken I will adjust so clicking image opens (after the merger).

**Comment by inorichi** [comment]
Hopefully the next weekend (maybe sooner if I can dedicate more time)

**Comment by CarlosEsco** [comment]
ok go ahead and close this I will wait til after conductor merger

**Comment by j2ghz** [comment]
@CarlosEsco Can you give the pull request a more descriptive name? Sometihng like `Add images and 'view chapters' to library updates`. Thanks.

**Pull request closed without merging**
