### PR TITLE
Translations (Continuous)

### PR DESCRIPTION
**Pull request by j2ghz**
**Merge just before next release** or when there's a significant amount of translations waiting
Don't merge if push healthcheck is not up: [Healthcheck](https://healthchecks.io/checks/9d0ad96f-ea6f-470d-911a-17ac190c5fec/details/)
Continues from #3312

More information: https://tachiyomi.org/help/contribution/#translation
[Translation status](https://hosted.weblate.org/engage/tachiyomi/?utm_source=widget)

### CODE REVIEW

**Comment by AriaMoradi** [comment]
merge please, I added Persian.

**Comment by arkon** [comment]
It'll be merged when we're ready.

**Comment by AriaMoradi** [comment]
also I think "fa" should be added to languages menu code

**Comment by milotype** [comment]
I've just updated Croatian by uploading it to Weblate. I'm not sure why, but all but one strings are marked as needing to be reviewed. But I can't change the state of these strings. Can you please change that. The only string not marked is the one I've translated directly in Webplate - it was a new string – "Disable".

**Pull request merged**
