### PR TITLE
Add Manga Fox Chapter titles if exist

### PR DESCRIPTION
**Pull request by CarlosEsco**
Addresses
#926 

null safe check to see if chapter title exists for a manga if so appends it to the chapter name.
Also adjusted chapter impl so that if a name changes from the source for an existing manga in library the name change will reflect in the existing chapters.

### CODE REVIEW

**Comment by CarlosEsco** [comment]
image

**Comment by inorichi** [comment]
I don't want to go through the chapter readded process if the title changes. In fact, it shouldn't do it if the scanlator changes. All that logic should go into the sync chapters with source method.

**Comment by CarlosEsco** [comment]
do you want to merge and discard chapters readded code.  I'll look into and open new pull request in the sync chapter with source method

**Comment by inorichi** [comment]
You can either add the mangafox part in the other PR or revert the changes to `ChapterImpl` here.

The sync method should silently update scanlator/title in the db if required (without adding them to the added/deleted chapters list).

You can use kotlin's `find` instead of `equals` with the `in` for collections if you think it's better.

**Comment by CarlosEsco** [comment]
removed chapterImpl equality stuff and changed sourceChapter filter and dbChapter Filter in ChapterSourceSync

**Comment by inorichi** [comment]
I was thinking of new logic once a chapter with the same url is found. You can check the title or the scanlator and store those that changed in a list `toChange` and update the db without adding them to `toAdd` or `toDelete`, because those trigger a new chapters notification.

I'll avoid changing the title though, because if the chapter is downloaded it'll be orphan.

**Comment by inorichi** [comment]
c0d7b16 This is what I meant.

**Comment by CarlosEsco** [comment]
yea see what you mean way more elegant solution

**Pull request closed without merging**
