### PR TITLE
Add download badge, and local badge for library view

### PR DESCRIPTION
**Pull request by CarlosEsco**
addresses #826 as well as adds badge to distinguish local manga from network ones.

screenshot_20170713-135602
screenshot_20170713-135608

### CODE REVIEW

**Comment by inorichi** [comment]
Showing downloaded chapters can slow a lot the library. It'll need to be configurable or totally rewrite the fetching method with a singleton (and maybe a filewatcher too).

**Comment by CarlosEsco** [comment]
@inorichi   I thought it might slow, and i could load test but i dont think its gonna be any slower than say having the download filter on.  The reason being is the download filter is doing almost the same thing.  

Download filter opens source folder for every manga does a listFiles and verifies its not empty.
This opens source folder for every manga does a listFiles and does size on listFiles.

**Comment by inorichi** [comment]
Yes, but downloaded filter is also optional, while this forces the lookup. 

It wouldn't be so bad if the `File` API were used, but the Storage Access Framework is painfully slow.

I think that option could be placed in the right drawer, below Display: List or Grid

**Comment by CarlosEsco** [comment]
Okay I'll add the option sometime this week

**Comment by CarlosEsco** [comment]
Added as an option

image

**Comment by blackdevil91** [comment]
hi, ive updated tachiyomi to the latest version but i dont have the badge option. sorry for any inconvenience. would be nice if receive some assistant

**Comment by CarlosEsco** [comment]
This is just a pull request that hasn't actually been added to the main library yet

**Comment by blackdevil91** [comment]
noted and sorry for the question

**Comment by CarlosEsco** [comment]
All good

**Comment by inorichi** [comment]
Sorry I've been delaying this one a lot. I'm making it the next priority.

**Comment by inorichi** [comment]
Merged manually in https://github.com/inorichi/tachiyomi/commit/d0567de4e6ce9fdc39f430ea45f04526dbe4290e and the next few commits.

**Pull request closed without merging**
