### PR TITLE
[WIP] Added option te delete chapter after reading.

### PR DESCRIPTION
**Pull request by NoodleMage**
Go to Setting > Downloads to toggle: default = false.

### CODE REVIEW

**Comment by LendLord** [comment]
Hi. Please add the option to remove penultimate chapter, because often you can accidentally go to the next chapter, but you can't go to previous chapter. This is particularly important for manga like noobless where pages are really long. 
Thanks.

**Comment by NoodleMage** [comment]
@LendLord. What do you exactly mean? It now deletes the chapter after you switch to the next one or when you go back when you're on the last page of a chapter.

Am I correct in assuming that you want an option where the chapter is not deleted after switching to the next chapter but only when you are 2 chapters ahead? Or do you mean there is a different option where you delete all mangas but the last one?

**Comment by LendLord** [comment]
Yes, I mean when you 2 charters ahead, it will be really great to have such option. 
Thanks!

**Comment by NoodleMage** [comment]
Okay. Will see what I can do ;). Thanks for the suggestion ;).

**Comment by NoodleMage** [comment]
Corrupted. Will rewrite + implement request from LendLord

**Pull request closed without merging**
