### PR TITLE
Options to backup app settings and extensions list

### PR DESCRIPTION
**Pull request by bairagyakushal4**
I would like the app to have the ability to backup and restore app settings and options , it would also be great if i can backup extensions list, Its problematic to remember them them and download them.

### CODE REVIEW

**Comment by CarlosEsco** [comment]
Why did you open a pull request?

**Comment by bairagyakushal4** [comment]
I wanted new feature for j2k, did I mess up again!

**Comment by CarlosEsco** [comment]
1.  This is not the J2K repo
2.  a new features request you should create an issue not a PR
3.  You basically opened a request to merge all of J2K into the main Tachiyomi app

**Comment by bairagyakushal4** [comment]
haha lol , sorry.

**Pull request closed without merging**
