### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by j2ghz**
Continuing the #881 PR.
More information: https://github.com/inorichi/tachiyomi/wiki/Translation
**Comment for translator access and new languages.**

Current status:
[Translation status](http://weblate.j2ghz.com/engage/tachiyomi/?utm_source=widget)

### CODE REVIEW

**Comment by j2ghz** [comment]
@cubakcabak Comment on the currently open pull request
Github login should be fixed, can you try again?

**Comment by cubakcabak** [comment]
yes, it work now.

thank you.

**Comment by yshalsager** [comment]
@j2ghz Arabic Translation is 100% Completed 👍

**Comment by Zyten** [comment]
HI @j2ghz , I'd like to contribute to Malay (ms-MY) translation. I have already registered at the weblate instance.

**Comment by j2ghz** [comment]
@Zyten https://weblate.j2ghz.com/projects/tachiyomi/main/ms/ done

**Comment by Zyten** [comment]
@j2ghz Thank you. I'll start working on it.

**Comment by Zyten** [comment]
Hi, I'm wondering how I could go about and test a translation that is yet to be merged? I pulled a fresh 0.63 release, added "values-ms" folder from the translations fork and added "ms" language code in SettingsGeneralController. The build does list the new language I added but it doesn't seem to work. In fact, none of the other languages work as well. Did I miss something in the build process? I wanted to see the translation in effect before making changes to certain strings that seem quite long compared to the source.

**Comment by j2ghz** [comment]
@Zyten Can you try the version from F-Droid? There should be a version with the latest translation merged available.

**Comment by Zyten** [comment]
@j2ghz I tried out fdroid.j2ghz.com/repo/tachiyomi-translation-10-b10.apk which seems to be the latest version but unfortunately the language I wish to see is not listed in the settings (ms-MY). I figured I should try to pull your translations fork and enable the new translation as I tried earlier but again, to no avail. I traced the commit history and the only change @inorichi did after merging the translations fork was to enable them in SettingsGeneralController and thus I'm not sure what I'm missing. 

I'm using Android Studio 3.0 with unmodified build.gradle from the repo, opting not to update anything. I built the project as I would a typical Java based Android project without any errors. The build installs in my connected device just fine. But when I choose a new language in Settings, the screen refreshes and stays in English. I tested 0.63 release APK on the same device, ensuring that it works as expected but when I download the 0.63 ZIP and build by myself, it doesn't.

I'm familiar with Android development but have never worked with a Kotlin project however. A little nod in the right direction should set me straight. Thank you!

**Comment by j2ghz** [comment]
I have little experience with android development, so you will have to wait for @inorichi , @noodlemage or any of the contributors to help you

I just noticed that sometimes you mention ms, sometimes ms-MY, could it be that?

_Sent from my HTC One A9 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by Zyten** [comment]
Alright. I'll do just that. Nope. I used ms-MY in conversation so that ms is not misunderstood to be an acronym of some sort. Within the code, I used ms everywhere. 
Actually, on second thoughts, this is not particularly urgent, so I suppose I could just wait for a new release which merges this PR and make changes after using the app in said language for a while. Thank you for your time and effort in helping to bring translations to the app!

**Comment by inorichi** [comment]
> But when I choose a new language in Settings, the screen refreshes and stays in English.

You have to select the `standard` or `fdroid` variant. The `dev` one doesn't include translations for a faster apk compilation.

**Comment by Zyten** [comment]
@inorichi That did it! Thank you!

**Pull request merged**
