### PR TITLE
Add chinese track website "bangumi"

### PR DESCRIPTION
**Pull request by feilongfl**
# add bangumi track

## todo 
- [x] login
- [x] search
- [x] get info(work to here, but i need some help)
- [x] push last read chapter
- [x] pull last read chapter
- [x] show status
- [x] change icon
- [x] set status

### CODE REVIEW

**Comment by feilongfl** [comment]
Because of the website limit, I can't get last read chapter index.
I am communicating with Bangumi.tv

**Comment by feilongfl** [comment]
After communicating with the Bungumi website, the corresponding interface has been added.

**Comment by feilongfl** [comment]
I have no idea why CI report `The command "yes | sdkmanager "platforms;android-27"" failed and exited with 127 during .`

**Comment by jojo233233** [comment]
@feilongfl  
有个小问题
下拉刷新的时候会获取到缓存

**Comment by feilongfl** [comment]
> @feilongfl
> 有个小问题
> 下拉刷新的时候会获取到缓存

I checked that this problem does exist. Because of the API returns the HTTP header `Cache-Control → max-age=3600`, okhttp use cache. It seems that I need to manually force refresh.

**Comment by feilongfl** [comment]
> I have no idea why CI report `The command "yes | sdkmanager "platforms;android-27"" failed and exited with 127 during .`

I check our issues,and find that travis ci build fail may caused by https://github.com/inorichi/tachiyomi/pull/2085

**Comment by feilongfl** [comment]
I think it's ready for merge.

**Comment by inorichi** [comment]
Thanks. I'll try to have it merged either on this or next weekend.

**Comment by inorichi** [comment]
I only reviewed the code but it looks good. I'll merge this but I won't maintain this tracker, so if there's any issue please open a new PR.

**Comment by feilongfl** [comment]
@inorichi I got it.

**Pull request merged**
