### PR TITLE
Move snackbarStyle

### PR DESCRIPTION
**Pull request by DarKCroX**
Move snackbarStyle from Theme.Base.Amoled to Theme.Base.Dark
close https://github.com/inorichi/tachiyomi/issues/2699

### CODE REVIEW

**Comment by DarKCroX** [comment]
ss

**Comment by CarlosEsco** [comment]
Not a fan.  it barely stands out

**Comment by arkon** [comment]
It should be light in the regular non-AMOLED dark themes to comply with the MD guidelines.

**Comment by CarlosEsco** [comment]
If you wanted to get fancy if the dark blue theme it could realistically be a blue snackbar.  But yea  it needs to be a gray at minimum if not white like other apps with dark modes

**Comment by DarKCroX** [comment]
I dont think I can change the text color using xml alone with material 1.1.0

> snackbarTextViewStyle requires the version 1.2.0

**Comment by arkon** [comment]
I'll just make it dark for now, but I'll do some other tweaks in my local branch too.

**Pull request closed without merging**
