### PR TITLE
Implement parsers for Readmanga, Mintmanga and Mangachan

### PR DESCRIPTION
**Pull request by Taumer**
Add parsers for 
http://readmanga.me/
http://mintmanga.com/
http://mangachan.ru/

### CODE REVIEW

**Comment by LendLord** [comment]
эхх, когда же сольют парсеры...
@Taumer, а такой еще вопрос планируешь ли в будущем добавлять еще парсеры?

**Comment by inorichi** [comment]
I will add an overridable method in the source to add custom parsing of the chapter. Doing it like that is unnecessary. I also have to make the sources language aware, or allow to enable/disable them individually.

**Comment by Taumer** [comment]
@LendLord, в ближайшее время - нет.

> I will add an overridable method in the source to add custom parsing of the chapter

@inorichi, thanks, I really don't like my approach to this. I'll rewrite this part when you add method

**Comment by inorichi** [comment]
https://github.com/inorichi/tachiyomi/commit/d4bb092543e030ddf89677499a65a668c0f95f7d#diff-d64413e9693a4eff5305fc2472fb1b6e

Override that method to have custom parsing. Keep in mind the property `url` of the chapter doesn't have the domain name at that point, so it will be something like: `/my_manga/56.html` or similar.

**Comment by inorichi** [comment]
Can you implement the new `getLang` method? It has to return `LanguageKt.getRU()`. Also remove ` (RU)` from `NAME`, it's not needed anymore.

When you're done, can you squash all the commits into a single one?

**Comment by Taumer** [comment]
@inorichi, done.

**Pull request merged**
