### PR TITLE
add tachiyomi://search/... intent-filter to prepopulate searchbox

### PR DESCRIPTION
**Pull request by dexmanga**
This gets used by inorichi/tachiyomi-extensions#974

### CODE REVIEW

**Comment by inorichi** [comment]
On 1.x I added a loading screen that directly opens the `MangaController` once the manga is added to db.

Using the search function works but tbh I don't like that a tap on a manga in the webpage opens the search screen... I'm wondering whether to port that feature here, because it's a nice addition and 1.x is going to take a while.

**Comment by inorichi** [comment]
Another thing I forgot. Since an extension provides  multiple sources, you have to select the language. We'd need another  screen to select the source that should handle the link... 1.x doesn't  have this issue since extension-sources are 1-1.

**Comment by dexmanga** [comment]
Thoughts on tachiyomi::/search/en/MangaDex/query ?

**Comment by inorichi** [comment]
But then we're assuming everybody uses the english source. Unless only one language is enabled, we have to let the user select the language. That's one of the reasons I hate the 1-N relationship on the current extensions. :disappointed:

**Comment by AmineI** [comment]
One way to avoid the languages issues in the current extensions would be to be able to do a "limited global search", basically global but only with the requested sources, without changing user settings - for example launch a global search in all the enabled mangadex sources only (no matter the language), and then the user would select his own as usual.

I actually had something like that in mind in #1787, but using a [search intent ](https://developer.android.com/reference/android/content/Intent.html#ACTION_SEARCH) instead of a custom url like tachiyomi://search, and that would trigger a global search and not a specific extension's search.
(I think your way with an URL would be easier for users to manually call than an intent though, didn't think of that at the time.)

**Comment by inorichi** [comment]
That could work. Probably the best solution we could have before 1.x

**Comment by inorichi** [comment]
I'll accept this PR if it's implemented as we discussed before, by using the global search.

The extension's activity handle should send to the main process its own package name, which can use later to filter results for that specific extension, and of course only the enabled languages/sources will show results.

This is how the redirecting activity is implemented in 1.x: https://github.com/inorichi/tachiyomi-extensions/blob/1.x/deeplink/src/main/java/tachiyomix/deeplink/SourceDeepLinkActivity.java
Note the `Intent.EXTRA_REFERRER`

If anyone wants to try this go ahead, if no one has assigned this by next week, I'll work on it.

**Comment by dexmanga** [comment]
Sounds like you want to change the `Source` interface to add the package?

**Comment by inorichi** [comment]
There's no need for that, you can check against the `ExtensionManager`.

**Comment by inorichi** [comment]
Anyone working on this? If not I'll probably implement it tomorrow.

**Comment by inorichi** [comment]
Closing in favour of 5619543

**Pull request closed without merging**
