### PR TITLE
Adding Sardinian ("sc") to the list of languages

### PR DESCRIPTION
**Pull request by asereze**
I've completed the Sardinian translation of the app 3 days ago, but since it's a new language I would like to add it to the list.

### CODE REVIEW

**Comment by inorichi** [comment]
The language isn't part of tachiyomi yet (open at #1886), so it's pointless to merge now. You can either keep this open until the other PR is merged or close it and I'll add it later.

I'd prefer the former so that I don't forget to enable new languages when I merge the translations.

**Comment by asereze** [comment]
Ok, I will keep it open, then.

**Comment by inorichi** [comment]
Enabled now.

**Comment by asereze** [comment]
Thank you!

**Pull request closed without merging**
