### PR TITLE
Changed the wording on some strings

### PR DESCRIPTION
**Pull request by cyalins**
Fixed grammar issues and reworded some strings for clarity

### CODE REVIEW

**Comment by wopian** [comment]
Uncomplete is the grammatically correct form.

Incomplete refers to something that isn't completed, with the intention of **never** getting completed.

Uncomplete refers to something that isn't completed, with the intention of getting completed.

**Comment by JohnFlowerful** [comment]
Uncomplete is not a word. Uncompleted is, though.

**Comment by cyalins** [comment]
Oxford and Merriam-Webster just define 'incomplete' as not being finished, so I guess it works in this case

[source](http://www.oxforddictionaries.com/definition/english/incomplete)

**Comment by wopian** [comment]
Better yet, use "Ongoing" to match what all the sources use.

"Only update ongoing manga"

**Pull request merged**
