### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by j2ghz**
Continuing the #844 PR.
Shields.io doesn't provide a shield for translations, had to use a direct one.
More information: https://github.com/inorichi/tachiyomi/wiki/Translation
Comment for translator access and new languages.

### CODE REVIEW

**Comment by Pavkazzz** [comment]
Hi, I'm Russian translator, can u give me access to contribute in future?

**Comment by UnrealPowerz** [comment]
@j2ghz I noticed some of the translations in certain languages are too long and get cut off (especially in settings), should they get shortened or will this be fixed with variable height stuff?

**Comment by j2ghz** [comment]
You have to ask @inorichi @NoodleMage, I don't know.

**Comment by j2ghz** [comment]
@Pavkazzz I gave you access

**Comment by yuukiw** [comment]
is german being worked on already? Otherwise i could do it or help with it.

**Comment by j2ghz** [comment]
@yuukiw I've added german, but you are not registered so I can't give you translator permissions

**Comment by yuukiw** [comment]
@j2ghz fixed, i am now registered there.

**Comment by j2ghz** [comment]
@yuukiw done

**Comment by j2ghz** [comment]
After problems with update the site is up again.

**Comment by j2ghz** [comment]
@inorichi Is 0.6.2 close? If so I'll fix the translations so they can be included.

**Comment by inorichi** [comment]
Not yet. I had plans to include these changes.

**Comment by cubakcabak** [comment]
i'd like to help with Indonesian translation, but translation web gave error every time i try to login with my (this) github id.

**Comment by mrskizzex** [comment]
Please give me translator access for polish language. I already added suggestions on weblate.

**Comment by yshalsager** [comment]
@j2ghz @inorichi i want to be Arabic Translator

**Comment by j2ghz** [comment]
@yshalsager added

**Comment by yshalsager** [comment]
@j2ghz Thanks, i started translating

**Pull request merged**
