### PR TITLE
Adjust 3 dot chapter menu to support Android 16

### PR DESCRIPTION
**Pull request by CarlosEsco**
Start/End not supported for android 16. #1220

### CODE REVIEW

**Comment by LinkCable** [comment]
Hey @CarlosEsco can you revert the list overflow menu back to horizontal, while keeping the same touch area?

screen shot 2018-01-29 at 10 15 29 pm

This looks very odd from a visual design perspective, there's no sense of hierarchy with both the header and list items using the same overflow menu.

**Comment by CarlosEsco** [comment]
So that image isn't quite right the vertical is more left however I changed it from horizontal cause that's what @inorichi requested

**Comment by LinkCable** [comment]
Hmm, I'd say Horizontal is better in this context, both to have a hierarchy under the top Overflow menu and that the content in the list is all horizontal as it's text, so a horizontal overflow menu fits in with the reading flow.

**Comment by wopian** [comment]
Tachiyomi is the only app I've seen use the horizontal overflow in list views (or at all) with the vertical still being used in the header, so this change is more consistent with the general usage

**Comment by CarlosEsco** [comment]
This is what v17+ looks like 
image

**Comment by LinkCable** [comment]
Hmm, I want to revisit this cell layout at some point, as there is really big empty space between the chapter name and the date/download/page info. 

But for this PR it's not necessary.

**Pull request merged**
