### PR TITLE
Show manga with no installed source

### PR DESCRIPTION
**Pull request by paronos**
I think it would be better to show a manga even when the corresponding extension is not installed. This would also be a solution for #1333 (would allow migration or deletion).

For now a stub source is added for each source id found in the database (since I do not know if this PR will be merged, for now there are no optimizations).

### CODE REVIEW

**Comment by inorichi** [comment]
Isn't it easier to return a default source in the `get` method?

Anyways this would need a lot of testing before merge.

**Comment by paronos** [comment]
Now the get method return a default source (placed in a map to avoid multiple incantations).
Also I removed the `Bototo` source since it was almost equal to `StubSource`. Maybe the other sources could also be removed (leaving everything to the extensions).

I did some tests (by installing and uninstalling extensions and then going to the "My library", "Library updates" and "Recently read" sections), but it can not be said to be "a lot of testing".

**Comment by Sparh4wk** [comment]
just wondering, isnt better solution to store information about catalogues in backup and force uset to install extensions stored there before restore?

**Comment by j2ghz** [comment]
Closes https://github.com/inorichi/tachiyomi/issues/762

**Comment by fam007e** [comment]
Could you please add "www.heavenmanga.life" site into the list...
This site enables some of the otherwise licensed manga to be read.

**Comment by inorichi** [comment]
Merged manually with a few modifications.

**Comment by fam007e** [comment]
I didn't understand.

**Pull request closed without merging**
