### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by j2ghz**
Continuing the #1747 PR.
More information: https://github.com/inorichi/tachiyomi/wiki/Translation

Current status:
[Translation status](https://hosted.weblate.org/engage/tachiyomi/?utm_source=widget)

### CODE REVIEW

**Comment by Soitora** [comment]
Finished the Swedish translation, how do I include it in a pull request? I'm sorry if I missed an instruction somewhere

**Comment by M4sy** [comment]
I've done the Czech translation. Can you merge it please? 😄 Thanks

**Comment by metroid112** [comment]
I don't know what happened with the Spanish translations in weblate but "Extención" should be "Extensión" but somehow they all got a "c" instead of "s" now.

**Comment by j2ghz** [comment]
@Credits125Cre did that in https://github.com/inorichi/tachiyomi/pull/1750/commits/5e40672dcc891b0a1c02719e9ef6b9029532031d
https://hosted.weblate.org/projects/tachiyomi/strings/es/#history

**Pull request merged**
