### PR TITLE
[Cloudflare] Fix 503 due to missing value in js challenge.

### PR DESCRIPTION
**Pull request by DitFranXX**
Related issues: inorichi/tachiyomi-extensions#951

From: Anorov/cloudflare-scrape#200

### CODE REVIEW

**Comment by DitFranXX** [comment]
just add a note here. 

A hidden value `s` was appears long ago but it is not need to solve a challenge until today.

**Comment by CarlosEsco** [comment]
sneaky sneaky

**Comment by buzmeg** [comment]
Kissmanga is still returning a 503 even with dev build r1471

**Comment by einstein95** [comment]
@buzmeg Did you clear your cookies

**Comment by Vanaks** [comment]
Hi all, after I installed dev build I'm having this error

Screenshot_20190321-142341

I tried to clear cookies, cache, going directly to readcomicsonline and coming back to the app and isn't working, besides that, the app is great

**Pull request merged**
