### PR TITLE
Catalog visuals update 1155

### PR DESCRIPTION
**Pull request by CarlosEsco**
I think everything was addressed for #1155  

Made drawer swipe to open/close
moved search/reset to bottom and swapped positioning
fix collapse bug
click search closes drawer
switched to arrow for sort

| |  |
|:---:|:---:|

### CODE REVIEW

**Comment by LinkCable** [comment]
Could you add a divider line above the search / reset buttons?

https://material.io/guidelines/components/dividers.html

**Comment by CarlosEsco** [comment]
image

**Comment by LinkCable** [comment]
Perfect, thanks @CarlosEsco! :)

**Comment by NoodleMage** [comment]
The arrow looks so big imo :O

**Comment by LinkCable** [comment]
I had it at 16px by 16px in my mockup. Not sure what the size is in this PR.

screen shot 2018-01-09 at 2 19 09 pm

**Comment by CarlosEsco** [comment]
i will mess with it alignment gets thrown off when smaller arrows are used.
24
image
16
image

**Comment by LinkCable** [comment]
Hmm, try 20dp? One seems too big, the other too small ha.

And weird how alignment is thrown off, I would imagine it's a tableview or something?

**Comment by CarlosEsco** [comment]
its thrown off because these views are all check boxes when not checked they have a transparent 32dp check.  Im modifiying the svg to be 32 with 24 icon to see if it looks better

**Comment by LinkCable** [comment]
Thanks @CarlosEsco, sorry there's that much work for a small UI change

**Comment by CarlosEsco** [comment]
too large? this 24 with 32 spacing
image

**Comment by LinkCable** [comment]
Can I be difficult and ask to see 20dp in 32dp as well? 😬

**Comment by CarlosEsco** [comment]
give me few i actually found a way to pad the vector in the xml instead of having to use inkscape to edit

**Comment by CarlosEsco** [comment]
super easy now let me know i can go larger or smaller 
image
image

**Comment by LinkCable** [comment]
The top one!

**Comment by cd0rw0** [comment]
Hi @CarlosEsco 

This PR for Catalog, any plan to do same for my library. ( maybe in another PR or something)
btw this Look improvement look good.
Thanks

**Comment by CarlosEsco** [comment]
Yes eventually

**Comment by LinkCable** [comment]
@NoodleMage @inorichi code review?

**Comment by inorichi** [comment]
LGTM but requires further testing because the flexible adapter library was updated and it's being used in almost every screen.

**Comment by CarlosEsco** [comment]
@inorichi i can double check but i dont know if i even need the update.  The main key was adding holder.itemView.setOnClickListener(holder) since the main change from v4 is onclick has to be set for click to work previous version there was a default click listener attached.  see below:
https://github.com/davideas/FlexibleAdapter/issues/479

**Comment by LinkCable** [comment]
Is this ready @CarlosEsco ?

**Comment by CarlosEsco** [comment]
Yep

**Pull request merged**
