### PR TITLE
increase touch area for 3 dot in chapter list

### PR DESCRIPTION
**Pull request by CarlosEsco**
#1166 

teal to highlight touch area

old
image

new
image

### CODE REVIEW

**Comment by inorichi** [comment]
I'd also move the icon further to the left and replace the svg with the vertical dots variant.

**Comment by CarlosEsco** [comment]
image

**Comment by inorichi** [comment]
That was too much :D. I'd say align in with the first dot of the vertical one.

**Comment by CarlosEsco** [comment]
image

**Pull request merged**
