### PR TITLE
Add new russian strings

### PR DESCRIPTION
**Pull request by Pavkazzz**
Added new russian strings 
@Taumer please review this

### CODE REVIEW

**Comment by Flat** [comment]
All translations are handled via weblate[1] @j2ghz 

1. http://weblate.j2ghz.com

**Comment by Pavkazzz** [comment]
I can't translate text via weblate, couse it show 100%
https://weblate.j2ghz.com/projects/tachiyomi/main/ru/

**Comment by j2ghz** [comment]
When new string are added I have to manually rebase. You can let me know at #1134 if you notice.

**Comment by Pavkazzz** [comment]
Oh, thx!

**Comment by Pavkazzz** [comment]
What should i do now, is this request will be merged or i need to rewrite this one in weblate?

**Comment by j2ghz** [comment]
I have cherry-picked your commit, and the changes are now available in weblate.
https://github.com/inorichi/tachiyomi/pull/1242/files#diff-350ed87a7debbc4439cbdc7f12bfca7eR417
This was already translated differently in weblate, so I didn't change it.

**Comment by Pavkazzz** [comment]
Thank you! It is amazing. I think you can close this request now.

**Pull request closed without merging**
