### PR TITLE
Implement parser for readmanga.today

### PR DESCRIPTION
**Pull request by na-ji**
Hello !

I quickly added a new parser for the website : http://readmanga.today/ 
I did it because it is the only site that's not blocked on my network. 

Ask me if I have anything to change !

### CODE REVIEW

**Comment by inorichi** [comment]
Can you update with the last master? You need to implement `getLang` and remove ` (EN)` from the name. Also the id will be 8.

**Comment by na-ji** [comment]
Should be good for now (sorry I merged too quickly)

**Comment by inorichi** [comment]
Can you squash them?
`git rebase -i upstream/master`, change every "pick" to "squash" (except the first one), close, enter the new commit message, and `git push -f`

**Comment by na-ji** [comment]
@inorichi : The PR should be mergeable now :+1:

**Comment by inorichi** [comment]
Okay, thanks :)

**Pull request merged**
