### PR TITLE
Hide Empty Search Results in Catalogues

### PR DESCRIPTION
**Pull request by MCAxiaz**
Solves https://github.com/inorichi/tachiyomi/issues/1732 https://github.com/inorichi/tachiyomi/issues/1809

Not sure on the exact UI (i.e. keep or hide the catalogue title), and if whether or not this should be in settings (can probably just remove the nothing_found view if not).

Also didn't see any value in showing a loading circle for catalogues that error out, so changed it to return an empty result.

### CODE REVIEW

**Comment by inorichi** [comment]
I just noticed this is similar to #2097. I'd probably wrap the source API call into a `Observable.defer` so that we make sure that call can never crash the app. And change onException with onError, since this handles a few more cases.

Not sure yet if I'll merge this or the other, I'd have to test which one behaves better.

**Comment by inorichi** [comment]
Can you fix conflicts? Basically you don't have to update the *Presenter anymore.

Btw, if I merge this we don't need the `nothing_found` view, right?

**Comment by MCAxiaz** [comment]
Yea, so I'll go ahead and just remove the the view then?

**Comment by inorichi** [comment]
If it's not going to be used, yeah.

**Comment by MCAxiaz** [comment]
Would the resources need to be removed as well?
I believe there's one string resource `@string/no_results` and one vector `ic_search_black_112dp` which don't appear to be used elsewhere.

**Comment by inorichi** [comment]
If the app still compiles after removing them it should be fine

**Comment by hXtreme** [comment]
Found this: 

httpss://www.randomlytyping.com/blog/2015/6/2/hunting-unused-android-resources-with-lint

Hope it helps.

**Comment by MCAxiaz** [comment]
> 
> 
> Found this:
> 
> httpss://www.randomlytyping.com/blog/2015/6/2/hunting-unused-android-resources-with-lint
> 
> Hope it helps.

Thanks, that was interesting. Now I know there were already 100+ unused resources LOL.
Wondering if that should be cleaned up 🤔

**Comment by hXtreme** [comment]
@MCAxiaz you should definitely open an issue with all the linting errors for resources.

**Pull request merged**
