### PR TITLE
Allow back button to navigate to previous URL in WebView

### PR DESCRIPTION
**Pull request by FlaminSarge**
Adds Forward, Refresh, and Close actions to webview controller menu

-----------------------------------------------
Things before this should be merged:

- Do I need to null-check 'web' since view comes from getView() instead of a param?
- How do I add a 'close' menu item for the web view controller so that if a user gets stuck in e.g. an ad-loop they can force the whole WebView to close (as pressing back used to do here)?

### CODE REVIEW

**Comment by arkon** [comment]
1. Probably not.
2. We ought to change the up button from a back arrow to a close (X) icon instead.

**Comment by FlaminSarge** [comment]
Since this page is a controller wrapping a webview, I wasn't sure if it was possible to change the back button's icon.

(Is there webview implementation we can use that doesn't require this kind of wrapping?)

**Comment by FlaminSarge** [comment]
So it turns out that the back button on the controller is also affected by this handleBack() change, so changing it to a close icon wouldn't be accurate unless we can swap it out entirely for a 'close' action. Trying to figure out how to do that, as I'm not too familiar with anything here.

**Comment by FlaminSarge** [comment]
I've updated this to work as the Samsung Internet and Chrome webviews work for the most part, with the exception of the button in the top left which is still 'back' (because the hardware back button is tied to that, unfortunately). Close is instead in the dropdown menu, as are Forward and Refresh; Forward only shows up if webview.canGoForward() is true.

Ready for review.

**Comment by joseph619** [comment]
@FlaminSarge Did you request for a review?

**Comment by FlaminSarge** [comment]
As in, the GitHub feature for it? I think that's limited to those with write access to the repo.

**Comment by joseph619** [comment]
@arkon This has been requested for review, but FlaminSarge doesn't have write access to formally request one

**Pull request merged**
