### PR TITLE
[WIP] F-Droid dev repo

### PR DESCRIPTION
**Pull request by j2ghz**
The removals are only so that I can test it on my fork, need to be reverted before merge
It needs the `$user/repo` (public) and `$user/fdroid-data` (private) repositories

- [x] Clone fdroid-data with repo submodule
- [x] Run fdroid update
- [x] Commit and push fdroid-data with repo submodule
- [ ] Change versionCode during build (latest: `<versioncode>4033</versioncode>`) PROBLEM: Travis does not have build numbers

Work NOT in progress as @CarlosEsco is working on autoupdater, so it may not be needed

### CODE REVIEW

**Comment by Poussinou** [comment]
Well sorry to bother you @j2ghz

We at F-Droid try to maintain a list of alternative repo for the F-Droid client. You can find it [here](https://forum.f-droid.org/t/known-repositories/721). The URL of your own repo has changed as far as I can see.

The [wiki](https://github.com/inorichi/tachiyomi/wiki/F-Droid-for-dev-versions) specifies that it's currently unavailable, but I currently use it. So what's the state of the repo?

By the way, as far as I can see, your archive repo doesn't exist anymore, is that right?

**Comment by j2ghz** [comment]
This one https://github.com/j2ghz/repo is there, it's just not receiving updates. I was hoping for a handover, but no one expressed interest in maintaining it.

**Comment by Poussinou** [comment]
Thanks for this really quick and clear answer.

We will keep this one at https://github.com/j2ghz/repo in the F-Droid list, even if you don't push updates there.

Please ping me in this thread if you change anything.

**Comment by j2ghz** [comment]
@Poussinou I think you can remove my repo. It's not going to be updated or maintained.

**Pull request closed without merging**
