### PR TITLE
Implement long hold selection for Manga Chapters

### LINKED ISSUE #1493: Download Feature Request: Range Selection
**App version:**
0.7.4
**Issue/Request:**

[REQUEST]  Can we have the range selection to download manga chapters. 
Eg. Select starting chapter then select ending chapter?
Then all the chapters between those will be downloaded

**Other details:**

I used this feature in other manga app and is very convenient to have. 

screenshot_2018-06-17-15-27-19-666

### PR DESCRIPTION
**Pull request by zhuoyang**
Long hold is functioned as "Select until from the last selection" (Inspired by Solid Explorer)
Closes #1493, alternative solution to #1641
[Demo here](https://streamable.com/2543q)

### CODE REVIEW

**Comment by inorichi** [comment]
Please fix the line endings of the file to what they were. I know there's a diff on github to exclude them but I'd rather not merge a small feature with big changes due to just line endings.

**Comment by hXtreme** [comment]
I can't seem to open the demo but from just the description, this seems like a feature that users won't notice for years because probably there are no UI cues that indicate this feature. 

An example of a no UI cue feature that gets it right:

Long pressing the manga name copies it to clipboard.

I say it gets it right because of the norm that long pressing text selects(highlights) it with options for copy, cut, and paste (of of which only copy makes sense in our context).

**Comment by zhuoyang** [comment]
> Please fix the line endings of the file to what they were. I know there's a diff on github to exclude them but I'd rather not merge a small feature with big changes due to just line endings.

Fixed, have you considers using LF project wide? so that git's "core.autocrlf" can handle commit from different platform without breaking line endings.



> I can't seem to open the demo but from just the description, this seems like a feature that users won't notice for years because probably there are no UI cues that indicate this feature.
> 
> An example of a no UI cue feature that gets it right:
> 
> Long pressing the manga name copies it to clipboard.
> 
> I say it gets it right because of the norm that long pressing text selects(highlights) it with options for copy, cut, and paste (of of which only copy makes sense in our context).

Agreed, however I seems to discover this features fairly quick when using Solid Explorer without UI cue.
The UI cue that I can think of is displaying toast message when user select more than 3 chapters in a row using single selection mode. What do you think of this idea?

**Comment by inorichi** [comment]
> Fixed, have you considers using LF project wide? so that git's "core.autocrlf" can handle commit from different platform without breaking line endings.

Yes, 1.x is entirely LF.

**Comment by Guiorgy** [comment]
> this seems like a feature that users won't notice for years because probably there are no UI cues that indicate this feature.

Well, here's a different example for inspiration: Novel Library is essentially like Tachiyomi but for novels. There they have a button in the context menu Select Between, which does exactly that, selects all chapters between the chapters you have selected, and only appears if you have at least 1 chapter selected.

Either way, I really hope some way to select in bulk is added, and this solution looks pretty elegant imo.

**Comment by Guiorgy** [comment]
If #1641 is merged, wouldn't this be unnecessary?

**Comment by zhuoyang** [comment]
> If #1641 is merged, wouldn't this be unnecessary?

Yes, but UI cue aside this implementation is much more convenient imo.

**Comment by Guiorgy** [comment]
@zhuoyang, indeed, your's is more.. elegant? Perhaps not too bad of an idea to implement both? Like, to each their own?

**Comment by arkon** [comment]
@zhuoyang Sooo I ended up making the project use LF instead. Would you be able to update your PR again? Otherwise I'll have to do it.

**Comment by arkon** [comment]
Nevermind, cherry picked a fixed version from @Jays2Kings 's fork: https://github.com/inorichi/tachiyomi/commit/2d3bfa9a89e08bb7318a39ba73620ae2820d6181

**Pull request closed without merging**
