### PR TITLE
New colors + theme attrs

### PR DESCRIPTION
**Pull request by InFlames03**
Added new colors.xml values and modified some themes.xml fields for a more tailored look between themes.

### CODE REVIEW

**Comment by CarlosEsco** [comment]
do you have some before and after screens you could post?

**Comment by InFlames03** [comment]
Screenshots as requested. Feel free to let me know if you need anything more! 👍 

[Before](https://imgur.com/a/6DljT)

[After](https://imgur.com/a/vrbCm)

**Comment by Flat** [comment]
| Before | After |
| --------- | -------- |
| before dark | after dark | 
before amoled | after amoled |

**Comment by InFlames03** [comment]
Dialogs blending in with colorBackground fixed (it bothers me and I'm pretty sure it would bother others too)

**Comment by Flat** [comment]
I'm not sure if it's my eyes or my monitor but the list items almost look like they have a green hue to me.

**Comment by InFlames03** [comment]
Yeah, it looks VERY green in your post above. Looks fine on my recent post and in person though. My guess would be that compression does wonders

**Comment by Flat** [comment]
I used an emulator to take screenshots. Looks the same in the emulator so might just be a quirk of that. Your screenshot does look a lot better.

**Comment by inorichi** [comment]
I'm ok with everything except changing the colors of the reader theme.

Screenshots of how it looks would be appreciated so that we can make a poll to decide if we'll change it (because this affects everyone, not only the users of the dark theme).

**Comment by InFlames03** [comment]
Screenshots for the reader theme's before and after? I'll gladly provide them but please give me a couple of days. 

Drowning in exams atm T_T

**Comment by NoodleMage** [comment]
Here is the poll:
https://www.strawpoll.me/15238395

Please vote will look at results in approximately 10 hours :)

**Pull request merged**
