### PR TITLE
Georgian translation

### PR DESCRIPTION
**Pull request by Rogavactive**
Added Georgian (ka-rGe , which is native for me) translation and entry in preferences.
Will update periodically.

### CODE REVIEW

**Comment by arkon** [comment]
This should have been done in Weblate.

@j2ghz do you see any issues if this is merged and then the language is added in Weblate?

**Comment by j2ghz** [comment]
If we follow:
1. Lock weblate
2. merge current weblate PR
3. merge this PR
4. do a pull in weblate
5. unlock weblate

it should be fine. Weblate will detect new language files automatically, no need to add it.

**Comment by arkon** [comment]
@Rogavactive For future edits, you can do them here: https://hosted.weblate.org/engage/tachiyomi

**Comment by Rogavactive** [comment]
Thank you, I will apply future changes from this website. @arkon

**Pull request merged**
