### PR TITLE
Fix the Design discrepancy with download queue

### PR DESCRIPTION
**Pull request by hXtreme**
Fixes [this issue](https://github.com/inorichi/tachiyomi/issues/1932)

### CODE REVIEW

**Comment by hXtreme** [comment]
Please let me know if you have any questions or queries.

**Comment by inorichi** [comment]
This was due to the downloads notification opening multiple fragments. With the activity it was easier to only allow one instance, plus easier to handle the intent.

If the transition is a concern, we can override the activity's transition with a fade.

**Comment by hXtreme** [comment]
More so than the transition, the back button behavior is a bit more irritating. For all other options, back button would take you to My Library but not for Download Queue. Also, I couldn't understand what you meant by multiple fragments. If yo could tell me more about it then I may be able to work a bit on that, hopefully leading to something.

**Comment by lenyer21** [comment]
Hey newbie here....Can anyone can tell me why the KissAnime and mangafox are not functioning in tachiyo

**Comment by hXtreme** [comment]
@lenyer21  this is not exactly the place for this question I'd suggest that you go to tachiyomi-extensions however, if I have to take a guess it's probably because of some new security feature they implemented.

**Comment by inorichi** [comment]
There's an intent handler that opens the download activity when you tap the downloads notification. I believe that'll be broken with this patch, as the intent now has to be handled by the `MainActivity`.

**Comment by inorichi** [comment]
I'll keep this the current way, it might be ugly but more changes than this are required.

**Pull request closed without merging**
