### PR TITLE
Optimize images

### PR DESCRIPTION
**Pull request by TacoTheDank**
Done with https://ezgif.com/optipng.

### CODE REVIEW

**Comment by AbdullahM0hamed** [comment]
OptimizationMan™

**Comment by CarlosEsco** [comment]
@arkon  is it time to retire the old book icon?  no reason to have old book, android 7 round icon, and the adapative icon for newer android devices

**Comment by arkon** [comment]
Why? It's still used by some launchers and older versions of Android.

**Comment by CarlosEsco** [comment]
sure but you can just make the default icon the round one.

**Comment by TacoTheDank** [comment]
Correct me if I'm wrong, but Android versions under Nougat can't access round icons, right? In that case, we need to keep it for versions below Nougat.

**Comment by CarlosEsco** [comment]
you would just do this

```
        android:icon="@mipmap/ic_launcher"
        android:roundIcon="@mipmap/ic_launcher_round"
```

to

```
        android:icon="@mipmap/ic_launcher_round"
```

**Comment by arkon** [comment]
I'd rather not shoehorn the rounded icon to versions where unique icon shapes are still the norm.

**Comment by TacoTheDank** [comment]
Sure

**Pull request merged**
