### PR TITLE
search other sources for library

### PR DESCRIPTION
**Pull request by CarlosEsco**
@inorichi up to you if you want to merge this or work or want something a little cleaner before merging.   This is for Batoto users that need to switch mostly. So worst case it doesnt get merged we can leave this hear for a month or so 

Here is apk for this dev version. 
https://www.dropbox.com/s/xmkrq5ncberxhod/tachiyomi-dev-search-other-sources.apk?dl=0
Steps to begin source search 

Thank @Flat for the update instructions:

1. Make a backup of manga
2. Uninstall dev version if installed
3. Install CarlosEsco's version
4. Import backup to CarlosEsco's version
5. Sort library by source
6. Select all batoto sources by long tapping and then tapping the rest
7. Tap search icon
8. Use global search to pick a new source
8.1 update tracking as well as mark your chapters read 
9. Hit back button on phone and the next manga will search
10. Repeat until done
11. Remove batoto mangas
12. Create a backup
13. Uninstall CarlosEsco's version
14. Import backup into the version you use daily
15. Profit

### CODE REVIEW

**Comment by LinkCable** [comment]
I'm thinking we should wait a bit to see what shakes out of this Batoto situation, if the staff members announce they are taking over the domain and preserve old links or whether they will create something entirely new, or if nothing comes out in a few days we can discuss some sort of migration tool or something.

**Comment by CarlosEsco** [comment]
agreed this is a quick solution for anyone wanting to just move off completely since who knows what is gonna happen

**Comment by ShakeBake** [comment]
Shoot. I just downloaded the dev app and I can't login to batoto or restore mangas from kissmanga.

**Comment by CarlosEsco** [comment]
@ShakeBake i pulled in the kissmanga cloudflare fix.  Please redownload and try again.

**Comment by ShakeBake** [comment]
👍

**Comment by DinduNuffins** [comment]
Reminder that you're gonna need ES File Explorer or an equivalent to install this version. Or I did, anyway.

**Comment by Lethiur1** [comment]
Unfortunately I can't install it. Always giving me an error while analyzing the package it seems. I'll wait for next dev release I suppose

**Comment by xChickens** [comment]
If you get an error analyzing the package make sure that the any version of Tachiyomi is uninstalled. There's conflicting signatures between this one and any other version.

**Comment by emyarod** [comment]
can we expect this PR to be merged in along with the cloudflare fix?

**Comment by Lethiur1** [comment]
@xChickens I did that, I created the backup and then uninstalled the app before trying to install, will try again but if it doesn't work I'll just wait.

**Comment by inorichi** [comment]
We're working on a more advanced alternative so I'd recommend you all to wait a bit more.

**Comment by wopian** [comment]
@LinkCable the Batoto staff aren't working on a new Batoto/taking over - said they'd only do it if all the clones/alternatives failed. They do have a dump though - but it's unsorted...

**Comment by inorichi** [comment]
I'm closing this PR to avoid people migrating everything like with this approach.

**Pull request closed without merging**
