### PR TITLE
New reader menu

### LINKED ISSUE #359: Issues with "Hide Status Bar" option.
Even with "Hide Satus Bar" on, the status bar reappears whenever I thouch the screen (like to scroll), never auto-hides again.

screenshot_2016-06-20-19-14-08

Version: v0.2.2-1
Android 4.2.2  - Samsung Duo GT-S7582

I also want to thank you for your work, great software! I absolutely love it!

### PR DESCRIPTION
**Pull request by inorichi**
Fixes #359 and implements #330

### CODE REVIEW

**Comment by fatimagrace015** [comment]
Follow for updates

**Comment by fatimagrace015** [comment]
Im not rushing nor mean to pressure y'all but is mangago source will be fixed just like last time??😭😭 Thats the only source I use aside for mrm😭😭

**Comment by CarlosEsco** [comment]
@lakotagray linked wrong issue but this has nothing to do with mangago. Go to the other repo for any updates.

**Comment by wopian** [comment]
@fatimagrace015 https://github.com/inorichi/tachiyomi-extensions/issues/368

**Pull request merged**
