### PR TITLE
Added a app loading splash Screen

### PR DESCRIPTION
**Pull request by markelgaston**
As a fix to #2158

Instead of a white background, the app now starts up with a custom theme (defined in "splash_nackground.xml") until the main activity loads, after which it will update the theme as always with our choosed theme on the settings.

Result: https://streamable.com/q8urq

### CODE REVIEW

**Comment by markelgaston** [comment]
> Add end of file newline.

oh, already fixed, thanks.



> Colour for build and Dev version should be different right? (dark blue and grey respectively)
> 
> Does anyone know how to do that?

i didnt know there were two different versions xD, ill take it a look at that later during the day.

**Comment by hXtreme** [comment]
[What the two versions look like](https://i.imgur.com/wxUNUQf.jpg)

**Comment by Soitora** [comment]
**Tachiyomi Stable** uses `#2E84BF` while **Tachiyomi Dev** uses `#455A64`.
What you're showing in your demonstration is for the Dev release.

**Comment by hXtreme** [comment]
Alternatively we can just use the colour from stable release.

Also, how about scaling the icon a bit, it looks too small.

**Comment by markelgaston** [comment]
> **Tachiyomi Stable** uses `#2E84BF` while **Tachiyomi Dev** uses `#455A64`.
> What you're showing in your demonstration is for the Dev release.

ohh i see, but where is the stable version? is it another branch?, and how do we usually convert a dev version to the stable version?

> Alternatively we can just use the colour from stable release.
> 
> Also, how about scaling the icon a bit, it looks too small.

To change the color you just have to change the color in splash_background.xml.

Yea, i also thought about that, ill scale it a bit bigger whenever i can, i have been a bit busy this days.

**Comment by markelgaston** [comment]
> Latest stable release: https://github.com/inorichi/tachiyomi/releases/tag/v0.8.4
> 
> I am not sure how tachiyomi does stable releases but you should ask on Discord.

Okay thanks ^^

**Comment by inorichi** [comment]
In `themes.xml` there's a `Theme.BrandedLaunch` that was never used because it didn't work. Please use that theme instead of a new one `styles.xml`. I'd also rename it to `Theme.Splash`.

About the color, I'd just use `#455A64` just because it's kind of dark (people was complaining about the white screen so...)

**Comment by arkon** [comment]
Going to work on this in a branch and submit another PR.

**Pull request merged**
