### PR TITLE
Update packagingOptions to exclude some META-INF

### PR DESCRIPTION
**Pull request by TacoTheDank**
META-INF really isn't needed, so let's Thanos snap it.

### CODE REVIEW

**Comment by Flat** [comment]
Does that mean we only delete half of it?

**Comment by TacoTheDank** [comment]
@Flat uhm... hrm... should've thought about it more

**Comment by arkon** [comment]
I'm a bit hesitant on this change. I think _some_ of it is useful?

**Comment by TacoTheDank** [comment]
@arkon If you're hesitant, I can change it to just exclude guaranteed pointless files.

Although, I've never experienced any sort of problem from an app that had nothing in META-INF.

Here's some related links:
- https://stackoverflow.com/questions/39305775/what-are-the-purposes-of-files-in-meta-inf-folder-of-an-apk-file/39305776
- https://discuss.kotlinlang.org/t/disable-meta-inf-generation-in-gradle-android-project/3830/6

**Comment by arkon** [comment]
It's just my gut feeling. If there's proof against it, I'm fine with excluding all of it.

**Comment by TacoTheDank** [comment]
Don't really need this tbh

**Pull request closed without merging**
