### PR TITLE
Applied bottom sheet theme

### LINKED ISSUE #3848: [Bug] Manga Chapter Filter improper overlay of navigation buttons
## Device information
* Tachiyomi version: 0.10.5
* Android version: 10
* Device: OP6

## Steps to reproduce
1. Open up manga info
2. Click filter
3. Notice space below filters slide

### Expected behavior
Filters slide should either cover up nav button or not make nav buttons invisible

### Actual behavior
Nav buttons are invisible, but can still be pressed, with an obnoxious wasted space

## Other details
[Video](https://cdn.discordapp.com/attachments/349436576037732355/759154092538462218/ScreenRecord-20200925-164648.mp4)

### PR DESCRIPTION
**Pull request by h4rz**
- Resolved #3848

### CODE REVIEW

**Comment by arkon** [comment]
A few issues still:

- The status and navigation bars are now black. This is sort of okay with dark themes, but the status icons are impossible to see in the white theme.
- Should probably be applied in the reader as well.

**Comment by h4rz** [comment]
@arkon, Could you share a screenshot for point 2, I didn't get that.

**Comment by arkon** [comment]
Color filter sheet in reader:

Screenshot_20201003-102116

Also applies for the settings sheet.

**Comment by arkon** [comment]
Superseded by d548c690d65e6e1de211e1f5b985d6c95b7b1cc7

**Pull request closed without merging**
