### PR TITLE
New reader

### LINKED ISSUE #569: Add GIF support
It's something that's included in some mangas. It would be nice to not have to open the browser for those pages.

### LINKED ISSUE #928: Sharing option isn't working
Tachiyomi v0.6.1

Steps to reproduce:

1. Open some manga (tried only local manga) in Tachiyomi.
2. Press and hold your finger on screen. A window will be displayed with "share" option.
3.  Choose "share" and then select one of available options (gdrive, one drive, send to pictures, gmail etc).

Result:
Nothing happens.

### LINKED ISSUE #930: keep zoom level for all pages
Hey, there's something I really want which is to keep zoom level for all the pages after i zoomed in the first time, or at least i can choose in the options to start new pages with 50% zoom or 60% or something like that 
I tried playing in the reader settings for anything like that but i couldn't get it to work

### LINKED ISSUE #1115: page share not working
version 0.6.6
build 6 dec 2017

page share function not working
when tried to share to whatsapp,telegram / other apps, either black screen showed or "sharing failed".

### LINKED ISSUE #1135: reader skips pages when using a bluetooth remote
I've tried multiple remotes and they all work well with perfectviewer and other readers, Tachiyomi always skips a page (it used to work fine in a previous version) see video for example of the issue 

https://www.dropbox.com/s/ds2migeh2vsl5t0/VID_20171227_215227.mp4?dl=0

### LINKED ISSUE #1253: [Minor Bug] Horizontal Progress bar doesn't show on tablet when reading Right to Left
Using the dev version r1343 from F-Droid on both my phone and tablet.
On my tablet when a manga is set to read from Right to Left the horizontal progress bar doesn't show up, just the round blue dot that moves. Soon as you change it to read from Left to Right (or any other mode that changes the progress bar direction to be left to right, even webtoon) it shows again, white section for unread, filled in blue section for read and everything. This happens in both rotated orientations.

This doesn't happen on the phone.

Its super minor as the progress dot itself is the most important thing to see, but wanted to report it anyway.

Here are the 2 devices resolutions/OS incase its relavant:
Samsung Galaxy Tab S3:
2048 × 1536
264 ppi
Android 7.0

Nexus 6P
2560 x 1440
580 ppi
Android 8.1

[Edit]
I was able to reproduce this in a Genymotion VM by selecting a Pixel C as a base and changing its resolution to be that of the Samsung Tab S3. Selected 240 ppi as well as it was the closest option.

### LINKED ISSUE #1331: Filename / Directory containing % will make Local Catalogues error
Version: 0.7

Issue: If we put directory / file with % on it's name, the local Catalog will error. On my case I put Ichigo 100% doujinshi on it. After removing the %, it will works as usual.

Steps to reproduce:

 1. Copy directory / zip files containing % on it's name
 2. Browse Local Catalog
 3. Nothing showed, and there's only an empty notification and retry button on the bottom of the screen.

### LINKED ISSUE #1360: Visual error in landscape mode
**App version:** 0.7.2

**Issue/Request:** When you open reader settings while in landscape mode, you see the drop-down arrows overlap with OK button and go beyond the two lines (above and bottom).

Android 8.1
Nexus 6p

screenshot_20180410-104345 2

### LINKED ISSUE #1381: [Feature Request] Release volume keys when page slider is visible
**App version:** 0.7.2

**Request:** There should be an option to release the volume keys when the page slider is visible.

Navigating pages with the volume slider is very nice, but at the moment you have to leave the app if you actually want to use them to change the volume. You can still do it if you open the navigation drawer, but it would be nice if you could just tap the screen, set the volume and tap the screen again to continue reading.

It works this way in most other reader apps too, like Moon+ Reader and if I recall correctly the old MangaRock as well.

### LINKED ISSUE #1516: Image sharing to Discord gives non-image extension
**App version:**
0.7.4

**Issue/Request:**
When sharing an image from Tachiyomi to Discord, the filename given has a non-image extension (one that isn't jpg, png, gif, etc.). This means that Discord shows it as a standard file upload rather than embedding the image.

**Steps to reproduce (if applicable)**

 1. Open any manga
 2. Press and hold on the image to open the sharing popup
 3. Assuming you have Discord installed, select Discord
 4. Finish sharing, then view your share

### LINKED ISSUE #1528: Request to remove the image displayed when Custom Brightness is opened
**App version:**
0.7.4
**Issue/Request:**

Please remove the image which is shown when Brightness Icon is tapped. Especially in landscape mode, that image blocks all the important features. That image itself has no use. Kindly remove it.

**Steps to reproduce (if applicable)**

 1. Remove that image view.

**Other details:**

### LINKED ISSUE #1545: Reader error because of cache behaviour on large chapters?
**App version:**
Latest, r1427 
**Issue/Request:**
Reader error because of cache behaviour on large chapters.
**Steps to reproduce (if applicable)**

 1.Open chapter 84 of one punch-man on mangadex (or any other large, chap 92 by /a/ works too, possibly other larger than 75 * 1024 * 1024 bytes.
 2.Wait a few seconds for the app to try to cache all pages.
 3.Go to next page. Error.
screenshot_20180725-105340

**Other details:**
Putting chapter pages to cache was not made to stop when cache is full of pages of same chapter. 
There is a need to check if the oldest entry page number is bigger than the current reading when adding each page. Evem then I don't know what to excpecting you go back and load other and it starts deleting pages that are the oldest one from cache order of entry but are next to the one you are reading.

Rewrite that caches based on page distance would be nice, caching pages of next chapter before you change. Split cache memory in half for old pages and for new pages?

### LINKED ISSUE #1547: Change last read page behavior
**App version:** v0.7.4

Current behavior when you're reading a chapter and exit it halfway is that it counts the page you're on as read and starts you off in the next page.
This has 2 issues:
1. If you're in webtoon mode where there's no page border, you might end up having one page "open" while you're reading the previous one, meaning that when you exit you'll be 2 pages ahead of where you were. Imagine you're at the bottom of page 11, at this point Tachiyomi might show page 12 at the bottom if you scroll into it, if you exit now when you open the chapter again you'll be on page 13.
2. Chapters with 1 page. For example, Tomo-chan, when you're reading a chapter and exit, it'll mark that chapter as read and since it'll try to put you on the "next page" it ends up on the next chapter, which ends up being marked as read. **When you exit a chapter with one page, the chapter after it is marked as read automatically.**

My suggestion is to simply load the chapter on your current page, instead of marking the current page you're in as "read" and putting you on the next one automatically when loading, load to the page you left off on.

### LINKED ISSUE #1580: [Request][Enhancement] Mouse Scrolling = change pages
The viewer that only support scrolling is WEBTOON... Others... Not supported

I'm using bluetooth/2.4GHz mouse to navigate through my phone.. If this feature is implement... Man! What ease will it be!

& if u can add a custom mapper for buttons on controller/mouse/keyboard would be more cool too... Thanks in advanced!

### PR DESCRIPTION
**Pull request by inorichi**
This is a complete rewrite of the old reader in order to fix a few annoying bugs and add new features.

I've surely missed some issues that are fixed with this PR, so please comment here if you find any.

Test APKs will be uploaded and updated here whenever there's a significant progress. Feedback will be appreciated. If you already use the dev version, you'll have to overwrite the installation, but you can safely use this version because the old reader is untouched and there's a setting to toggle the new one.

**Beta 1**: [link](https://github.com/inorichi/tachiyomi/files/2259845/app-standard-debug.apk.zip)
**Beta 2**: [link](https://github.com/inorichi/tachiyomi/files/2263411/app-standard-debug.apk.zip)
**Beta 3**: [link](https://github.com/inorichi/tachiyomi/files/2270153/app-standard-debug.apk.zip)
**Beta 4**: [link](https://github.com/inorichi/tachiyomi/files/2286144/app-standard-debug.apk.zip)
**Beta 5**: [link](https://github.com/inorichi/tachiyomi/files/2321476/app-standard-debug.apk.zip)
**Beta 6**: [link](https://github.com/inorichi/tachiyomi/files/2340010/app-standard-debug.apk.zip)

TODO:

- [x] Implement basic reader functionality
- [x] Add a setting to test the new reader
- [x] Webtoon: Zoom the entire view instead of individual images (subsampling is disabled. Fixes #930)
- [x] Pager: properly support R2L reader without view rotations (Fixes #1253)
- [x] Pager: implement vertical reader with the support library's ViewPager and coordinates swapping
- [x] Pager: disable built-in keys navigation (Probably fixes #1135)
- [x] Support animated GIFs (crop borders and scale types are not supported. Fixes #569)
- [x] Include an additional page for chapter transitions 
- [x] Lazy load pages (up to 7 pages ahead can be loaded. Fixes #1545)
- [x] Preload next chapter pages when reaching the end
- [x] Preload previous chapter pages when the transition page is active
- [x] Load compressed formats without ContentProviders. Add a recycle method to release resources when appropiate (Fixes #1331)
- [x] Notify state of the chapter transition loading. Show a retry button if it fails
- [x] Use a determinate progress bar component without text
- [x] Show initial progress bar when the reader is opened
- [x] Save chapter progress and mark as read
- [x] Update tracking services
- [x] Update history
- [x] Restore background color but through themes instead of runtime checks
- [x] Restore reader settings dialog. Consider using a bottom sheet instead, it'd fix #1360
- [x] Restore reader brightness and color filter feature and dialog
- [x] Restore reader menu animation
- [x] Restore fullscreen reading
- [x] Restore long tap on page
- [x] Restore volume keys navigation
- [x] Restore delete downloaded chapters
- [x] Disable volume keys navigation when the menu is open (Fixes #1381)
- [x] Webtoon: require the bottom edge of a page to be visible before marking it as active page (Fixes #1547)
- [x] Color filter sheet: Use another layout for landscape mode (Fixes #1528)
- [x] Update Image decoder with fork that supports WebP
- [x] Improve image sharing, avoid using `Uri` to support all the possible sources (Fixes #1516,   fixes #1115 and fixes #928)
- [x] Add a progress dialog that prevents interaction when the next/prev chapter button is clicked
- [x] Pager: change pages with scroll wheel events (Fixes #1580)
- [x] Documentation
- [ ] Improve UX of the chapter transitions page for both pager and webtoon readers (future PR)

### CODE REVIEW

**Comment by kappa7194** [comment]
> Lazy load pages (up to 7 pages ahead can be loaded. Fixes #1545)

Sometimes when reading a chapter and advancing to the next page the page is not displayed and the "Retry" button is shown. Tapping the button correctly loads the page, however when this happens all of the remaining pages are affected by the issue, unless you go back to the chapter list and reopen the chapter, then the pre-load works again for a couple of pages and then breaks again.

I haven't been able to find any issue on this (#635 is similar but not the same), should this problem be fixed with the new reader or should I open a new issue about it?

**Comment by inorichi** [comment]
That's issue #1545

**Comment by inorichi** [comment]
Beta 1 added.

**Comment by inorichi** [comment]
Beta 2 added with long tap feature (set as cover, share, save) and full touch and hardware keys navigation.

**Comment by nurupo** [comment]
Curious, what website serves WebP images?

**Comment by inorichi** [comment]
Mangarock.

**Comment by tippl** [comment]
This reader fixes having to swipe across the entire screen to switch pages in right to left reader on android 9. It however breaks it for the vertical reader, so you need to swipe almost the entire height of the device to switch a page.

Android: 9 PPR1.180610.009
Version: Beta 3
Phone: Pixel 2

**Comment by inorichi** [comment]
It should work now.

**Comment by jsilvermist** [comment]
With the new viewer in portrait mode with sizing set to `Fit height` and using the `Left to Right` viewer while having the default set to `Right to Left`, `Automatic` zoom start position is putting it in the middle instead of the left like it used to.

**Comment by cloud1250x4** [comment]
Zipped chapter?

**Comment by einstein95** [comment]
Using Beta 4 with "Remove after read" set to "Last read chapter", the downloaded chapter does not get automatically deleted.

**Comment by ruudschouten** [comment]
Using Beta 4 tracking of manga isn't updated after reading a chapter. When confirm before updating is set to true, no confirmation is shown.

**Comment by inorichi** [comment]
Added beta 5 which includes updating trackers, deleting downloaded chapters and a bunch of fixes.

**Comment by inorichi** [comment]
By the way, as of beta 5 the old reader has been deleted.

**Comment by einstein95** [comment]
Running beta 5 and not deleting read chapters seems to happen on occasion, but not often enough for it to be easily reproduced.

**Comment by AmineI** [comment]
I'm also having issues with updating the "last read" sorting (it doesn't update anymore, no matter if I open a chapter, mark it as read, or read it).

**Comment by inorichi** [comment]
I was just missing a call to update the last read chapter when closing the reader.

Fixed in beta 6 alongside a rewrite of the subsampling scale view project which should load any image without issues. The decoder setting was removed for this reason.

About updating the deleted chapters on UI... it might be quite hard to fix. It'd probably require a lot of changes on the UI side + notifications from backend, and the priority is going to be low since it's just the UI getting out of sync.

**Comment by jsilvermist** [comment]
Wooo WebP support in the image decoder! Thanks!

**Comment by Pavkazzz** [comment]
@inorichi it is possible to repaint page after scroll to next page for e-ink users?
Because now it repaint page, each 15 second

**Comment by inorichi** [comment]
There's no timer whatsoever to repaint pages. I don't know what eink uses to trigger a refresh, but the UI code is about the same as before.

**Comment by Pavkazzz** [comment]
@inorichi Before it doesn't too :) It's possible to force repaint page after open next chaper page?

**Comment by jsilvermist** [comment]
@Pavkazzz Not sure what the logistics for that would be, but I can imagine 2 problems it could cause.

1. When you change pages, it could cause a flash as the page repaints.
2. If you change pages quickly, it could add a perceived lag before it becomes responsive and animates again after each page.

**Comment by Pavkazzz** [comment]
@jsilvermist as a separeted version for e-ink it will be nice anyway

**Comment by nurupo** [comment]
Yeah, no harm in having an option in settings to force repaint.

I don't understand why are there Android devices that use e-ink in the first place, if they have such issues. It can't be that Tachiyomi is the only application with such visual issues.

**Comment by Pavkazzz** [comment]
@nurupo usual they have a single app for reading books, which is realy optimized for this.
Option will be perfect, thx

**Comment by Ryogo-Z** [comment]
> There's no timer whatsoever to repaint pages. I don't know what eink uses to trigger a refresh, but the UI code is about the same as before.

This is a device specific issue, for sure.
Screen refresh implementation depends on e-ink controller used / android version / specific android implementation.

**Pull request merged**
