### PR TITLE
christmas app icon for Tachiiyomi 

### PR DESCRIPTION
**Pull request by lowzijian**
**I have created a new Christmas festive app icon for Tachiyomi** and added a few comments on navigation.header.xml to understand the code easier
tachiyomi Christmas app icon

I plan to do further on building the new theme layout for Christmas Season. This is my suggestion for the color changes

color.xml

   

    <color name="colorAccentChristmas">#A0011D</color>
    <color name="textColorPrimaryChristmas">@color/md_black_1000_87</color>
    <color name="textColorSecondaryChristmas">@color/md_black_1000_54</color>
    <color name="textColorHintChristmas">@color/md_black_1000_38</color>
    <color name="dividerChristmas">@color/md_black_1000_38</color>
    <color name="rippleColorChristmas">@color/md_black_1000_12</color>
    <color name="statusBarChristmas">@color/md_white_1000</color>
    <color name="appBarChristmas">@color/md_white_1000</color>
    <color name="backgroundChristmas">@color/md_white_1000</color>
    <color name="dialogChristmas">@color/md_white_1000</color>
    <color name="selectorColorChristmas">#A0011D</color>
    <color name="iconColorChristmas">@color/md_black_1000</color>

@inorichi @FlaminSarge @j2ghz  I hope you will like it

### CODE REVIEW

**Comment by LinkCable** [comment]
...what prompted this?

Anyways, this icon is way to busy to be displayed as an app icon (imagine it on a 4" screen, in a notification shade). Too much background texture and you removed the icon 立 which is how most users probably identify the app off their homescreen/drawer.

Also note that there's currently no way for an app to have two icons, so it wouldn't make sense for a whole new release just to push and then reset the app icon. If you want this icon I suggest using a launcher like Nova or Apex that allows you to set a custom icon for your phone.

**Comment by arkon** [comment]
IIRC it was for a school assignment.

**Comment by lowzijian** [comment]
@LinkCable i did this for my school assignment. i will close the pull request soon after the end of my current semester

**Comment by LinkCable** [comment]
@lowzijian Ok, nbd was just wondering! Hope the design feedback was helpful.

**Pull request closed without merging**
