### PR TITLE
New translation system

### PR DESCRIPTION
**Pull request by j2ghz**
Direct access: https://weblate.j2ghz.com/projects/tachiyomi/main/
Wiki: https://github.com/inorichi/tachiyomi/wiki/Translation

[Translation status](http://weblate.j2ghz.com/engage/tachiyomi/?utm_source=widget)

If you want to be added to the Translators group that can translate and accept suggestions (anonymous and Users can only suggest and vote) leave a message here. It would be good to have at least one translator for each language.

If you can translate a language that is not on the list let me know, it will be added.

Leave your feedback about the new system here.

### CODE REVIEW

**Comment by j2ghz** [comment]
I see you have been making suggestions: https://weblate.j2ghz.com/changes/

I would rather not confirm suggestions for languages I don't speak (which is none of them) from anonymous people while checking them using Google Translate.

If you want translator permissions, leave a comment.

**Comment by maurus56** [comment]
I can help with the Spanish translations, there seems to be a lot of words with "long" translations or ones where the word no longer works in the context. I'll keep on suggesting in those until it works out.

**Comment by UnrealPowerz** [comment]
I could help with translating to Dutch, it is not yet on the list though.

**Comment by j2ghz** [comment]
@maurus56 When you register and send me your username, I'll give you translator permissions, so you can not only suggest, but actually translate.

@UnrealPowerz When you are registered it should be possible to add a new language using this button: http://i.imgur.com/nPyq2VI.png

**Comment by maurus56** [comment]
Registered with this github account, username: maurus56

**Comment by j2ghz** [comment]
I added Dutch, and gave you both translator permissions

**Comment by UnrealPowerz** [comment]
@j2ghz I can now add languages, but i can only suggest translations. Is this normal? Is just suggesting ok?

**Comment by j2ghz** [comment]
@UnrealPowerz It should work now

**Comment by maurus56** [comment]
The spanish translation is almost finished. While reviewing some of the words it seems that many used different words for the same translation (eng:"default" , sp:"por defecto" "predeterminado"). I'll start the proofreading tomorrow or late next week.

**Comment by j2ghz** [comment]
@maurus56 If you want to define that a word or expression e.g. default should always be translated as "por defecto" you can add it to glossary, so the translations stay consistent.
http://i.imgur.com/8Kjnoxa.png

**Comment by j2ghz** [comment]
One-time notification for previous translators in case they want to complete their translations:
@Rinto-kun @Neverest @Horoneru @paronos @blackgin @MrAmnesiac @Pavkazzz @namnguyendeveloper

**Comment by blackgin** [comment]
Here I am for Italian. Registered with github and available as translator

**Comment by j2ghz** [comment]
@blackgin Added

**Comment by Pirmais** [comment]
Interested in translating Latvian and Russian. Potentially German as well.

**Comment by j2ghz** [comment]
@Pirmais I added you to translators, and added Latvian. I want to avoid having empty languages so if you want to start on German now let me know, if not, let me know once you do.

**Comment by Rinto-kun** [comment]
Checking in for Bulgarian language.

**Comment by j2ghz** [comment]
@Rinto-kun you have to register (or login with github) before I can give you any permissions

**Comment by Rinto-kun** [comment]
@j2ghz Registered.

**Comment by Horoneru** [comment]
I was thinking about that the other day, about how we could go on with the translation process without it becoming too cumbersome.

I can continue the translation in french.

**Comment by j2ghz** [comment]
@Horoneru @Rinto-kun added to translators

**Comment by nevaend** [comment]
I can help with the Arabic translations but when i open the project he gives me that
	Gradle build finished with 15 warnings(s)
and all in layout in palette in project 
So what i can do to solve that

**Comment by j2ghz** [comment]
@nevaend You don't need to open the project to translate. You can use weblate: https://github.com/inorichi/tachiyomi/wiki/Translation

After you are registered let me know, I'll give you permissions to translate

**Comment by nevaend** [comment]
if i need to open the project without any problem what i do

**Comment by j2ghz** [comment]
@nevaend If you have any specific problem with opening the project open another issue for that and describe the issue properly

**Comment by nevaend** [comment]
what i do to translate

**Comment by j2ghz** [comment]
@nevaend Go to https://weblate.j2ghz.com/translate/tachiyomi/main/ar/?type=nottranslated and you can translate the Source field into the translation field. Then click suggest.

**Comment by UnrealPowerz** [comment]
I finished the French translation since noone else was doing it. My french is a little rusty though so it would be nice if someone could go over them (or at least the ones marked for review).

**Comment by j2ghz** [comment]
After server maintenance weblate is back online

**Comment by Hypeouseaus** [comment]
I would like to help with Korean which is not yet on the list.

**Comment by j2ghz** [comment]
@Hypeouseaus Korean was added, permissions were given.

**Comment by Horoneru** [comment]
@UnrealPowerz Whenever I get some actual free time I'll continue those translations
Unfortunately, I'm really busy those days...

**Comment by RubeensVinicius** [comment]
Is it possible to add variants of a language? I can help with the translation for Brazilian Portuguese.

**Comment by j2ghz** [comment]
@RubeensVinicius It is. I gave you the translator access.

**Comment by Jendrej** [comment]
@j2ghz I would like to make a Polish translation. My name on Weblate is same as here.

**Comment by j2ghz** [comment]
@Jendrej Polish added, translator access given.
***
### Any further comments/requests should be opened at  #881

**Comment by yuukiw** [comment]
is german being worked on already? Otherwise i could do it or help with it.

**Pull request merged**
